export const config = {
  VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
  VITE_SUPABASE_SERVICE_ROLE_KEY: import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY,
  OPENAI_API_KEY: import.meta.env.VITE_OPENAI_API_KEY,
  REDDIT_CLIENT_ID: import.meta.env.VITE_REDDIT_CLIENT_ID,
  REDDIT_CLIENT_SECRET: import.meta.env.VITE_REDDIT_CLIENT_SECRET,
  YOUTUBE_API_KEY: import.meta.env.VITE_YOUTUBE_API_KEY
};